##### 1. What does Pandas stand for?
Python data analysis

##### 2. What are the 2 collections used in Pandas?
series, dataframes

##### 3. Name 4 things Pandas can do for us.
data cleaning, data fill, visualization, statistical analysis 

##### 4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
inplace=True

##### 5. What is a CSV?
file with comma separated values

##### 6. When cleaning data what values do we not like in our data?
null values, values out of range (input errors)

##### 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`

In [13]:
import numpy as np
array7 = np.array([[1, 2], [3,4], [5, 6], [7,8], [9, 10], [11,12]])
array7a = array7.reshape(2,3,2)

##### 8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

In [15]:
array8 = np.linspace(0,20, num=6)
print(array8)

[ 0.  4.  8. 12. 16. 20.]


##### 9. Make a Deep Copy of the above array

In [19]:
import copy
array9 = copy.deepcopy(array8)
print(array9)

[ 0.  4.  8. 12. 16. 20.]


##### 10. Concatenate these 3 arrays into a new array named 'newArray'...
    ```python
            ([[25, 16]])
            ([[11, 2], [13, 4]])
            ([[7, 81], [5, 6], [11, 12]])
    ```

In [20]:
array10a = np.array([[25, 16]])
array10b = np.array([[11, 2], [13, 4]])
array10c = np.array([[7, 81], [5, 6], [11, 12]])
newArray = np.concatenate((array10a, array10b, array10c))
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


##### 11. Sort 'newArray' in order into 'sortedArray'

In [22]:
sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


##### Question 12 was removed by instructors.

##### 13. Combined and sort the following arrays into one called 'comboArray' ...

    ```python
        one = ([10, 11, 12, 13, 14, 15, 16, 17])
        two = ([20, 21, 22, 23, 24, 25, 26, 27])
        three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
array13a = np.array([10, 11, 12, 13, 14, 15, 16, 17])
array13b = np.array([20, 21, 22, 23, 24, 25, 26, 27])
array13c = np.array([0, 1, 2, 3, 4, 5, 6, 7])
comboArray = np.sort(np.concatenate((array13a, array13b, array13c)))
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


##### 14. Take 'comboArray' and perform the following slicing activities:
    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving forward, every 5th element.

In [41]:
print("The 2nd element:", comboArray[1])
print("All elements from the 3rd to the last:", comboArray[2:])
print("All elements from the 4th to the 14th:", comboArray[3:14])
print("The last 6 elements:", comboArray[-6:])
print("All the elements from #0 up to and including #15:", comboArray[:-10])
print("Every even element from #20 to the end:", comboArray[-8::2])
print("From the last element moving forward, every 5th:", comboArray[0:-1:5])

The 2nd element: 1
All elements from the 3rd to the last: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
All elements from the 4th to the 14th: [ 3  4  5  6  7 10 11 12 13 14 15]
The last 6 elements: [22 23 24 25 26 27]
All the elements from #0 up to and including #15: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
Every even element from #20 to the end: [20 22 24 26]
From the last element moving forward, every 5th: [ 0  5 12 17 24]


##### 15. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object

In [5]:
import pandas as pd
ingredients = pd.Series(["----", "Flour", "Milk", "Eggs", "Spam"], name='Ingredients')
quantity = pd.Series(["----", 4, 1, 2, 1], name='Quantity')
unit = pd.Series(["----", "cups", "cup", "large", "can"], name='Unit')

Dinner = pd.DataFrame(ingredients).join(quantity)
Dinner = pd.DataFrame(Dinner).join(unit)
print(Dinner)

  Ingredients Quantity   Unit
0        ----     ----   ----
1       Flour        4   cups
2        Milk        1    cup
3        Eggs        2  large
4        Spam        1    can


##### 16. Take this data and create a DataFrame named studentData
    ```Python
        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
    ```

In [7]:
import pandas as pd
name = pd.Series(['Jai', 'Janusha', 'Gauray', 'Anuj'], name='Name')
height = pd.Series([5.1, 6.2, 5.1, 5.2], name='Height')
qual = pd.Series(['Msc', 'MA', 'Msc', 'Msc'], name='Qualification')
address = pd.Series(['Delhi', 'Doha', 'Chennai', 'Dakar'], name='Address')
pet = pd.Series(['Dog', 'Bunny', 'Chinchilla', 'Parrot'], name='Pets')
sport = pd.Series(['Darts', 'Basketball', 'Paddleboarding', "Cricket"], name='Sport')

studentData = pd.concat([name, height, qual, address, pet, sport], axis=1)
print(studentData)

      Name  Height Qualification  Address        Pets           Sport
0      Jai     5.1           Msc    Delhi         Dog           Darts
1  Janusha     6.2            MA     Doha       Bunny      Basketball
2   Gauray     5.1           Msc  Chennai  Chinchilla  Paddleboarding
3     Anuj     5.2           Msc    Dakar      Parrot         Cricket


##### 17. Add a new column to the DataFrame with the following deserts:
        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [8]:
dessert = pd.Series(['Ice Cream', 'Cashew Fudge', 'Waffles', 'Carrot Halwa'], name='Dessert')
studentData = pd.DataFrame(studentData).join(dessert)

print(studentData)

      Name  Height Qualification  Address        Pets           Sport  \
0      Jai     5.1           Msc    Delhi         Dog           Darts   
1  Janusha     6.2            MA     Doha       Bunny      Basketball   
2   Gauray     5.1           Msc  Chennai  Chinchilla  Paddleboarding   
3     Anuj     5.2           Msc    Dakar      Parrot         Cricket   

        Dessert  
0     Ice Cream  
1  Cashew Fudge  
2       Waffles  
3  Carrot Halwa  


##### 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [9]:
studentData.sort_values(by = ['Name', 'Address'], inplace=True)
print(studentData)

      Name  Height Qualification  Address        Pets           Sport  \
3     Anuj     5.2           Msc    Dakar      Parrot         Cricket   
2   Gauray     5.1           Msc  Chennai  Chinchilla  Paddleboarding   
0      Jai     5.1           Msc    Delhi         Dog           Darts   
1  Janusha     6.2            MA     Doha       Bunny      Basketball   

        Dessert  
3  Carrot Halwa  
2       Waffles  
0     Ice Cream  
1  Cashew Fudge  


##### 19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

    ```python
        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
    ```

In [12]:
df = pd.DataFrame({'Cows': [12,20], 'Goats': [22,19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')

##### 20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [25]:
vegName = pd.Series(['zucchini', 'eggplant', 'bell pepper', 'broccoli', 'kale'], name='Vegetable')
sun = pd.Series(['Full Sun', 'Full Sun', "Full Sun", "Part Sun", "Shade"], name='Sunlight Needs')
harvest = pd.Series(['August', 'June and July', 'July and August', 'September', 'October'], name='Harvest Time')
nightshade = pd.Series([False, True, True, False, False], name='Nightshade Family')

vegData = pd.concat([vegName, sun, harvest, nightshade], axis=1)
vegData.to_csv('vegetables.csv')

tomato = pd.Series(['tomato', 'Part Sun', 'June and July', True], index=['Vegetable', 'Sunlight Needs', 'Harvest Time', 'Nightshade Family'])
vegData2 = pd.concat([vegData, tomato.to_frame().T], ignore_index=True)
vegData2.to_csv('vegetables2.csv')